# Dockerfile
FROM python:3.11-slim

# environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# work directory
WORKDIR /app

#  dependencies
COPY requirements.txt /app/
RUN pip install --upgrade pip && pip install -r requirements.txt

COPY . /app/

# command
CMD ["gunicorn", "core.wsgi:application", "--bind", "0.0.0.0:8000"]
